-- Write your PostgreSQL query statement below
WITH T AS (
    SELECT BOOK_ID, COUNT(*) BORROWED
    FROM BORROWING_RECORDS
    WHERE RETURN_DATE IS NULL
    GROUP BY BOOK_ID
)

SELECT L.BOOK_ID
, L.TITLE
, L.AUTHOR
, L.GENRE
, L.PUBLICATION_YEAR
, L.TOTAL_COPIES CURRENT_BORROWERS

FROM LIBRARY_BOOKS L
    JOIN T
        ON L.BOOK_ID = T.BOOK_ID
WHERE T.BORROWED - L.TOTAL_COPIES = 0
ORDER BY CURRENT_BORROWERS DESC, L.TITLE;        